FROM python:3.8-slim AS bot

ENV PYTHONFAULTHANDLER=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONHASHSEED=random
ENV PYTHONDONTWRITEBYTECODE 1
ENV PIP_NO_CACHE_DIR=off
ENV PIP_DISABLE_PIP_VERSION_CHECK=on
ENV PIP_DEFAULT_TIMEOUT=100

# Env vars

ENV TELEGRAM_USERNAME ${TELEGRAM_USERNAME}
ENV TELEGRAM_ID ${TELEGRAM_ID}
ENV TELEGRAM_HASH ${TELEGRAM_HASH}
ENV KUCOIN_MAIN_KEY ${KUCOIN_MAIN_KEY}
ENV KUCOIN_MAIN_SECRET ${KUCOIN_MAIN_SECRET}
ENV KUCOIN_MAIN_PASS ${KUCOIN_MAIN_PASS}
ENV FTX_C1 ${FTX_C1}
ENV FTX_C1_HASH ${FTX_C1_HASH}
ENV FTX_READONLY_C1 ${FTX_READONLY_C1}
ENV FTX_READONLY_C1_HASH ${FTX_READONLY_C1_HASH}


RUN apt-get update
RUN apt-get install -y python3 python3-pip python-dev build-essential python3-venv

RUN mkdir -p /
ADD . /
WORKDIR /

RUN pip3 install -r requirements.txt
RUN chmod +x app.py

CMD python3 app.py;
